name: Build TrollStore IPA

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
    - name: Build and Sign
      run: |
        xcodebuild -project StepsWrite.xcodeproj -scheme StepsWrite -configuration Release -sdk iphoneos \
                   CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO archive
        
        brew install ldid
        mkdir -p Payload
        cp -R build/Release-iphoneos/StepsWrite.app Payload/
        
        # 샌드박스 우회 특수 Entitlements 생성
        cat <<EOF > ent.plist
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://apple.com">
        <plist version="1.0"><dict>
            <key>com.apple.developer.healthkit</key><true/>
            <key>com.apple.private.security.no-sandbox</key><true/>
            <key>platform-application</key><true/>
        </dict></plist>
        EOF
        
        ldid -Sent.plist Payload/StepsWrite.app/StepsWrite
        zip -r StepsWrite.ipa Payload

    - uses: actions/upload-artifact@v4
      with:
        name: TrollStore-IPA
        path: StepsWrite.ipa
